version: 1

disable_existing_loggers: False

formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: log/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: log/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    single_relation_extraction:
        level: DEBUG
        handlers: [console]
        propagate: False
    batch_relation_extraction:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler]
        propagate: False
    word_quality:
        level: DEBUG
        handlers: [console, error_file_handler]
        propagate: False
    preprocess:
        level: DEBUG
        handlers: [console, error_file_handler]
        propagate: False
    entity_linking:
        level: DEBUG
        handlers: [console]
        propagate: False
    clustering:
        level: DEBUG
        handlers: [console]
        propagate: False
    construct_graph:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler]
        propagate: False

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
